[BitTorrent]
TrackerEnabled=true
Session\DefaultSavePath=/torrents/completed
Session\LSDEnabled=false
Session\Port=LISTENING_PORT
Session\QueueingSystemEnabled=true
Session\UseRandomPort=false

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Bittorrent\LSD=false
Connection\PortRangeMin=LISTENING_PORT
Downloads\SavePath=/torrents/completed
General\UseRandomPort=false
Queueing\QueueingEnabled=true
WebUI\Address=*
WebUI\ServerDomains=*
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=false
WebUI\UseUPnP=false
Advanced\trackerPort=TRACKER_PORT
Advanced\trackerPortForwarding=true